### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by dryabchenko** [mixmaxhq/electron-editor-context-menu#1]
Hello, there are some problems with importing dependencies:

`var BrowserWindow = require('electron').BrowserWindow;`
`var Menu = require('electron').Menu;`

need to be changed to 

`var remote = require('remote');`
`var BrowserWindow = remote.require('browser-window');`
`var Menu = remote.require('menu');`

Because now BrowserWindow and Menu are undefined

**Comment by wearhere** [comment]
Hi @dryabchenko, sorry for the late response on this!

This module is meant to be required like this as documented [in the README](https://github.com/mixmaxhq/electron-editor-context-menu#usage):

```js
// `remote.require` since `Menu` is a main-process module.
var buildEditorContextMenu = remote.require('electron-editor-context-menu');
```

Perhaps it would have been nice to hide the `remote.require`s inside the module but then again I like that this makes explicit that this module has main-process dependencies. The other way, you could get bitten if you tried to `require` this module from a main-process module since `remote` wouldn't be defined.

Given that the usage is documented, I'd only change this if you could show that it was Electron convention to hide `remote.require`s inside the module. Could you point me to a few examples?

**Comment by wearhere** [comment]
Closing pending further comment.
